ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "coachName" VARCHAR(120);

CREATE TABLE IF NOT EXISTS "Coach" (
  "id" TEXT PRIMARY KEY,
  "name" VARCHAR(120) NOT NULL UNIQUE,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
