-- Enable Row Level Security on public tables (Supabase Data API / anon key).
-- Prisma uses the postgres role over DATABASE_URL, which bypasses RLS, so app behavior is unchanged.
-- Run once in Supabase SQL Editor or via `psql` after migrations.

ALTER TABLE IF EXISTS "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Coach" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "CoachCommissionRemittance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Attendance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Admin" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Service" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Payment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "SplitPayment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "ClientAnnouncement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "LoyaltyLedger" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "LoyaltyClaim" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "AddOnSubscription" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "WalkInAccessCode" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "WalkInPass" ENABLE ROW LEVEL SECURITY;
